# Generated by Django 4.2.1 on 2023-05-08 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='계정')),
                ('nickname', models.CharField(blank=True, max_length=15, verbose_name='별명')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소')),
                ('profile_img', models.ImageField(blank=True, upload_to=None, verbose_name='프로필 이미지')),
                ('category', models.CharField(blank=True, choices=[('cat', '고양이'), ('dog', '개'), ('bird', '새'), ('fish', '물고기'), ('snail', '달팽이'), ('stone', '돌'), ('turtle', '거북이')], max_length=10, verbose_name='반려동물 종류')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('followings', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
